version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: AzMine
      MONGO_INITDB_ROOT_PASSWORD: AzMine
      MONGO_INITDB_DATABASE: AzMineDB
      MONGO_INITDB_COLLECTIONS: Trashcans
    ports:
      - 27017:27017